### ISSUE TITLE
Can't compile renderer.debug.hxml

### ISSUE THREAD

**Issue by LucasMW** [deepnight/ldtk#210] opened 2020-11-10 21:09 UTC
haxe renderer.debug.hxml fails

Tried on master,  last git tag and last building commit

`haxe renderer.debug.hxml `
> src.data/data/def/TilesetDef.hx:88: lines 88-112 : Object requires field averageColors
> src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int, pxHei : Int, padding : Int, opaqueTiles : Null<Array<Int>>, identifier : String } should be ldtk.TilesetDefJson
> src.data/data/def/TilesetDef.hx:88: lines 88-112 : { uid : Int, tileGridSize : Int, spacing : Int, savedSelections : Array<{ mode : Dynamic, ids : Array<Int> }>, relPath : Null<String>, pxWid : Int,... has no field averageColors
> src.data/data/Level.hx:35: lines 35-41 : Object requires fields: worldY, worldX
> src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } should be ldtk.LevelJson
> src.data/data/Level.hx:35: lines 35-41 : { uid : Int, pxWid : Int, pxHei : Int, layerInstances : Array<ldtk.LayerInstanceJson>, identifier : String } has no field worldX

`haxe --version`

> 4.1.4

`haxelib list`

> castle: [git]
> deepnightLibs: 1.0.53 [git]
> electron: [git]
> format: [3.5.0]
> heaps: [git]
> hxnodejs: 12.1.0 [git]
> ldtk-haxe-api: [git]

**Comment by n67094** [comment] 2020-11-10 21:33
Duplicate of #208

**Comment by deepnight** [comment] 2020-11-11 07:39
Closed duplicate :)

**Closed by deepnight** 2020-11-11 07:39 UTC
