### ISSUE TITLE
Move entities off-grid when the grid is disabled

### ISSUE THREAD

**Issue by nyalloc** [deepnight/ldtk#590] opened 2022-01-30 23:10 UTC
When the grid is enabled, entity positions are clamped to the grid when they are created, and entity positions are clamped to the grid when they are moved. Disabling the grid allows you to place entities on a pixel-by-pixel basis, but does not allow you to move entities on a pixel-by-pixel basis, you can still only move them on the grid. It would be more intuitive if having the grid disabled allowed free, pixel-by-pixel movement.

This gif demonstrates the inconsistent behavior of the editor with regards to entity positions and the grid:

![ezgif-3-31f7f99ebe](https://user-images.githubusercontent.com/7504843/151721801-76a56990-2531-4695-9817-c2dc6863e80e.gif)

**Comment by deepnight** [comment] 2022-02-03 11:19
Thanks for reporting :)
Duplicate of #304

**Closed by deepnight** 2022-02-03 11:19 UTC
