### ISSUE TITLE
[Request] Fixing some part of autolayer assistant  that feel a little awkward

### ISSUE THREAD

**Issue by hyperkvlt** [deepnight/ldtk#822] opened 2023-01-18 03:54 UTC
I dont know whether is it just me, but I think some part of autolayer assistant feel a little awkward. Here's the screenshot:

### Screenshot:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/RgmRnPK/ldtk.png" alt="ldtk" border="0"></a>

**Comment by JustusPan** [comment] 2023-01-21 07:59
Please don't change this standard once we released one. Because we may start make some "templates" for it.
![image](https://user-images.githubusercontent.com/10916383/213854709-00d83147-2302-4931-9da9-c863e48da9c2.png)
like this

**Comment by deepnight** [comment] 2023-01-23 08:44
There's some improvement to be done here for sure. 
I'm closing this one as it's kind of duplicate of #482

**Closed by deepnight** 2023-01-23 08:44 UTC
