### ISSUE TITLE
Entity on the edge of the level is removed on resize

### ISSUE THREAD

**Issue by valryon** [deepnight/ldtk#1014] opened 2023-12-06 07:45 UTC
Hello!

We found a bug 😅
If you place an entity on the edge of the map (y = 0 or y = level_max for example) and if you resize the level on the other axis, the entity is deleted.

![inputbug](https://github.com/deepnight/ldtk/assets/155884/157ad0cb-4d3f-46bd-8e37-8623715ed942)

We're using LDtk 1.4.1.
Thanks for you work ❤️

**Comment by deepnight** [comment] 2023-12-10 09:05
That's not really a bug: 544px is not within the level bounds, as they are from 0px to 543px included. But the issue is more that the entity bounds are still over the level bounds, and deletion is counter intuitive :)

**Comment by deepnight** [comment] 2023-12-10 09:07
Related #684

**Comment by deepnight** [comment] 2023-12-29 10:10
This should be fixed in 1.5 update :)
Closing duplicate #684

**Closed by deepnight** 2023-12-29 10:10 UTC
Labels: 🪳 Bug
