### ISSUE TITLE
Move multiple levels at once

### ISSUE THREAD

**Issue by Fypur** [deepnight/ldtk#747] opened 2022-11-12 22:13 UTC
As of right now to move multiple levels, we need to tediously move them one at a time remembering their positions relative to each other. It would be nice that when we are in world view, we could hold shift to select multiple levels and then move them.

**Comment by BurgerBob** [comment] 2023-01-19 19:53
Duplicate of 
https://github.com/deepnight/ldtk/issues/596

**Closed** 2023-01-19 22:05 UTC
