### ISSUE TITLE
PNG Export cutoff

### ISSUE THREAD

**Issue by mrlovelies** [deepnight/ldtk#371] opened 2021-02-02 20:04 UTC
Having a problem with intGrid layer PNG exports getting cut off. Seems to be directly affected by both Width and Height of the level.

Level size: 640H/512W

Attached: Project view of "Hub" level, generated PNG of the "Walls" intGrid layer.

Expected Behaviour: All tiles of the intGrid layer would be account for in the intGrid layer PNG output.

What's happening: PNG is being cutoff.

Notes:
- The PNG will include more from the bottom if the height is reduced.
- The PNG will include more from the bottom if the level width is increased closer to the level height. 

![0000-Hub--02-Walls-int](https://user-images.githubusercontent.com/2262076/106655789-d258bd80-6567-11eb-8e6b-796a02ed3eff.png)
![LDtk-Project-View](https://user-images.githubusercontent.com/2262076/106655790-d2f15400-6567-11eb-94ee-29f30040e047.jpg)

**Comment by deepnight** [comment] 2021-02-19 15:18
I can't reproduce the issue on my side: could you please mail me the project file that has the bug? ldtk@deepnight.net

**Comment by deepnight** [comment] 2021-02-22 12:13
It will be fixed in 0.8 :)

**Closed by deepnight** 2021-02-22 12:13 UTC
Labels: bug
